---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/tetragon/main/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crypto-mining-detection
spec:
  kprobes:
    - call: "security_bprm_check"
      syscall: false
      return: false
      selectors:
        # Known crypto mining binaries
        - matchBinaries:
            - operator: "In"
              values:
                - "xmrig"
                - "minerd"
                - "ccminer"
                - "ethminer"
                - "claymore"
                - "cgminer"
                - "bfgminer"
                - "t-rex"
                - "phoenixminer"
                - "lolminer"
                - "nbminer"
          matchActions:
            - action: Post
        # Curl/wget piping to shell (common crypto miner installation)
        - matchBinaries:
            - operator: "In"
              values:
                - "curl"
                - "wget"
                - "/bin/bash"
                - "/bin/sh"
                - "/usr/bin/bash"
                - "/usr/bin/sh"
          matchActions:
            - action: Post
