---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/tetragon/main/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: suspicious-network
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      return: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchArgs:
            # Monitor connections to common C2/malware ports
            - index: 0
              operator: "DPort"
              values:
                - "4444"  # Metasploit
                - "5555"  # Android Debug Bridge / Malware
                - "6666"  # IRC bots
                - "31337"  # Elite/Back Orifice
                - "8080"  # Common proxy/C2
                - "9001"  # Tor
                - "1337"  # Common backdoor
                - "12345"  # NetBus
          matchActions:
            - action: Post
