---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teamspeak
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      teamspeak:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: teamspeaksystems/teamspeak6-server
              tag: latest
            env:
              TZ: Europe/Warsaw
              TSSERVER_LICENSE_ACCEPTED: accept
              TSSERVER_DEFAULT_PORT: "40000"
              TSSERVER_VOICE_IP: 0.0.0.0
              TSSERVER_FILE_TRANSFER_PORT: "40001"
              TSSERVER_FILE_TRANSFER_IP: 0.0.0.0
              TSSERVER_QUERY_SSH_ENABLED: "true"
              TSSERVER_QUERY_SSH_PORT: "40002"
              TSSERVER_QUERY_SSH_IP: 0.0.0.0
              TSSERVER_QUERY_HTTP_ENABLED: "true"
              TSSERVER_QUERY_HTTP_PORT: "40003"
              TSSERVER_QUERY_HTTP_IP: 0.0.0.0
              TSSERVER_QUERY_IP_ALLOWLIST: 0.0.0.0/0
              TSSERVER_VOICE_UDP_THREADS: "5"
              TSSERVER_DATABASE_CLIENT_KEEP_DAYS: "90"
              TSSERVER_LOG_PATH: /var/tsserver/logs
              TSSERVER_QUERY_TIMEOUT: "600"
            envFrom:
              - secretRef:
                  name: teamspeak-secret
            probes:
              liveness:
                enabled: true
                type: TCP
                spec:
                  port: 40000
              readiness:
                enabled: true
                type: TCP
                spec:
                  port: 40000
              startup:
                enabled: true
                type: TCP
                spec:
                  port: 40000
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 9987
        runAsGroup: 9987
        fsGroup: 9987
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: teamspeak
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          lbipam.cilium.io/ips: 10.10.0.52
          external-dns.alpha.kubernetes.io/hostname: ts.vzkn.eu
        ports:
          voice:
            port: 40000
            targetPort: 40000
            protocol: UDP
          filetransfer:
            port: 40001
            targetPort: 40001
            protocol: TCP
          serverquery-ssh:
            port: 40002
            targetPort: 40002
            protocol: TCP
          webquery:
            port: 40003
            targetPort: 40003
            protocol: TCP

    persistence:
      data:
        existingClaim: teamspeak
        globalMounts:
          - path: /var/tsserver
