---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name screego-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        server.config: |
          SCREEGO_EXTERNAL_IP=dns:ipv4.vzkn.eu

          # A secret which should be unique. Is used for cookie authentication.
          SCREEGO_SECRET=test1

          # If TLS should be enabled for HTTP requests. Screego requires TLS,
          # you either have to enable this setting or serve TLS via a reverse proxy.
          SCREEGO_SERVER_TLS=false
          # The TLS cert file (only needed if TLS is enabled)
          SCREEGO_TLS_CERT_FILE=
          # The TLS key file (only needed if TLS is enabled)
          SCREEGO_TLS_KEY_FILE=


          SCREEGO_SERVER_ADDRESS=0.0.0.0:5050
          SCREEGO_TURN_EXTERNAL_IP=dns:turn.vzkn.eu
          SCREEGO_TURN_EXTERNAL_PORT=3478
          SCREEGO_TURN_EXTERNAL_SECRET={{ .TURN_SECRET }}

          # Deny/ban peers within specific CIDRs to prevent TURN server users from
          # accessing machines reachable by the TURN server but not from the internet,
          # useful when the server is behind a NAT.
          #
          # Disallow internal ip addresses: https://en.wikipedia.org/wiki/Reserved_IP_addresses
          # SCREEGO_TURN_DENY_PEERS=0.0.0.0/8,10.0.0.0/8,100.64.0.0/10,127.0.0.1/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,239.0.0.0/8,255.255.255.255/32,::/128,::1/128,64:ff9b:1::/48,100::/64,2001::/32,2002::/16,fc00::/7,fe80::/10
          #
          # By default denies local addresses.
          SCREEGO_TURN_DENY_PEERS=::/128,::1/128,fe80::/10

          # If reverse proxy headers should be trusted.
          # Screego uses ip whitelisting for authentication
          # of TURN connections. When behind a proxy the ip is always the proxy server.
          # To still allow whitelisting this setting must be enabled and
          # the `X-Real-Ip` header must be set by the reverse proxy.
          SCREEGO_TRUST_PROXY_HEADERS=false

          # Defines when a user login is required
          # Possible values:
          #   all: User login is always required
          #   turn: User login is required for TURN connections
          #   none: User login is never required
          SCREEGO_AUTH_MODE=none

          # Defines origins that will be allowed to access Screego (HTTP + WebSocket)
          # The default value is sufficient for most use-cases.
          # Example Value: https://screego.net,https://sub.gotify.net
          SCREEGO_CORS_ALLOWED_ORIGINS=https://screego.vzkn.eu

          # Defines the location of the users file.
          # File Format:
          #   user1:bcrypt_password_hash
          #   user2:bcrypt_password_hash
          #
          # Example:
          #   user1:$2a$12$WEfYCnWGk0PDzbATLTNiTuoZ7e/43v6DM/h7arOnPU6qEtFG.kZQy
          #
          # The user password pair can be created via
          #   screego hash --name "user1" --pass "your password"
          SCREEGO_USERS_FILE=

          # Defines how long a user session is valid in seconds.
          # 0 = session invalides after browser session ends
          SCREEGO_SESSION_TIMEOUT_SECONDS=0

          # Defines the default value for the checkbox in the room creation dialog to select
          # if the room should be closed when the room owner leaves
          SCREEGO_CLOSE_ROOM_WHEN_OWNER_LEAVES=true

          # The loglevel (one of: debug, info, warn, error)
          SCREEGO_LOG_LEVEL=debug

          # If screego should expose a prometheus endpoint at /metrics. The endpoint
          # requires basic authentication from a user in the users file.
          SCREEGO_PROMETHEUS=false
  dataFrom:
    - extract:
        key: coturn
