---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentry
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./clickhouse/ks.yaml
  - ./kafka/ks.yaml
  - ./sentry/ks.yaml
