---
# yaml-language-server: $schema=https://schemas.vzkn.eu/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud-push
  annotations:
    gatus.home-operations.com/endpoint: |-
      group: self-hosted
      url: https://cloud.vzkn.eu/push/
spec:
  hostnames: ["cloud.vzkn.eu"]
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /push/
      backendRefs:
        - name: nextcloud-push
          namespace: self-hosted
          port: 7867
