---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden
            namespace: external-secrets
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      organizationID: 0b735120-9979-4e4d-a116-b24e00a9ec4d
      projectID: d78877ca-d005-4973-b288-b24e00bdef1d
