---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bambu-studio
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      bambu-studio:
        type: statefulset
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/bambustudio
              tag: 02.04.00
            env:
              TZ: Europe/Warsaw
              PUID: "1000"
              PGID: "100"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
                gpu.intel.com/i915: 1
          storage:
            image:
              repository: pldubouilh/gossa
              tag: v1.1.2
            env:
              TIMEZONE: Europe/Warsaw
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44 # video
          - 109 # render
    service:
      bambu-studio:
        controller: bambu-studio
        ports:
          http:
            port: 3000
          storage:
            port: 8001
    configMaps:
      config:
        data:
          .filebrowser.json: |-
            {
              "port": 8080,
              "baseURL": "",
              "address": "",
              "log": "stdout",
              "database": "/config/database.db",
              "root": "/srv"
            }
    route:
      bambu-studio:
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: home-automation
        hostnames:
          - bambu-studio.vzkn.eu
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: bambu-studio
                port: 3000
      storage:
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: home-automation
        hostnames:
          - bambu-storage.vzkn.eu
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: bambu-studio
                port: 8001
    persistence:
      config:
        existingClaim: bambu-studio
        advancedMounts:
          bambu-studio:
            app:
              - path: /config
            storage:
              - path: /shared
      config-file:
        type: configMap
        identifier: config
        advancedMounts:
          bambu-studio:
            storage:
              - path: /config/.filebrowser.json
                subPath: .filebrowser.json
      tmpfs:
        type: emptyDir
        advancedMounts:
          bambu-studio:
            app:
              - path: /tmp
              - path: /run
              - path: /var/log
