---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
spec:
  interval: 1h
  path: ./kubernetes/apps/external-secrets/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: &certApiVersion cert-manager.io/v1
      kind: &certKind Certificate
      name: bitwarden-tls-certs
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: *certApiVersion
      kind: *certKind
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-store
spec:
  healthChecks:
    - apiVersion: &secretApiVersion external-secrets.io/v1
      kind: &secretKind ClusterSecretStore
      name: bitwarden
  healthCheckExprs:
    - apiVersion: *secretApiVersion
      kind: *secretKind
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/external-secrets/external-secrets/store
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
  wait: true
