---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coder
  annotations:
    gatus.home-operations.com/endpoint: |-
      group: development
spec:
  hostnames:
    - "coder.vzkn.eu"
    - "*.coder.vzkn.eu"
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - name: coder
          namespace: development
          port: 80
