[env]
# File paths
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

_.file = [
  "{{config_root}}/.secrets.env",
]

[tools]
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
"go:github.com/evilmartians/lefthook" = "latest"
"uv" = "latest"
"pipx:flux-local" = "latest"
