---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vzkn-eu
spec:
  secretName: vzkn-eu-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: vzkn.eu
  dnsNames:
    - "vzkn.eu"
    - "*.vzkn.eu"
    - "*.s3.vzkn.eu"
