---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vzkn-eu-tls
spec:
  secretStoreRefs:
    - name: bitwarden
      kind: ClusterSecretStore
  selector:
    secret:
      name: vzkn-eu-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &tls-crt tls.crt
        remoteRef:
          remoteKey: INGRESS_NGINX_TLS_CRT
          property: *tls-crt
    - match:
        secretKey: &tls-key tls.key
        remoteRef:
          remoteKey: INGRESS_NGINX_TLS_KEY
          property: *tls-key
