---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sentry-kafka-cluster
spec:
  dependsOn:
    - name: kafka-operator
      namespace: database
  healthCheckExprs:
    - apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/sentry/kafka
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: sentry
  timeout: 10m
  wait: false
