---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  # - ./bazarr/ks.yaml
  - ./flaresolverr/ks.yaml
  # - ./lidarr/ks.yaml
  # - ./metube/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  # - ./qui/ks.yaml
  - ./radarr/ks.yaml
  # - ./recyclarr/ks.yaml
  # - ./slskd/ks.yaml
  - ./sonarr/ks.yaml
  # - ./soularr/ks.yaml
  - ./tqm/ks.yaml
  - ./webhook/ks.yaml
