---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mattermost-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        MM_FILESETTINGS_AMAZONS3ACCESSKEYID: "{{ .AWS_ACCESS_KEY_ID }}"
        MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        # Email
        MM_EMAILSETTINGS_SMTPSERVER: "{{ .SMTP_ADDR }}"
        MM_EMAILSETTINGS_SMTPPORT: "587"
        MM_EMAILSETTINGS_SMTPUSERNAME: "{{ .SMTP_USER }}"
        MM_EMAILSETTINGS_SMTPPASSWORD: "{{ .SMTP_PASS }}"
        MM_EMAILSETTINGS_ENABLESMTPAUTH: "true"
        MM_EMAILSETTINGS_CONNECTIONSECURITY: STARTTLS
        MM_EMAILSETTINGS_FEEDBACKNAME: "mattermost"
        MM_EMAILSETTINGS_FEEDBACKEMAIL: "{{ .SMTP_USER }}"
        MM_EMAILSETTINGS_REPLYTOADDRESS: "{{ .SMTP_USER }}"
        MM_SUPPORTSETTINGS_SUPPORTEMAIL: "{{ .SMTP_USER }}"
  dataFrom:
    - extract:
        key: protonmail
    - extract:
        key: mattermost-bucket
