---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app clickhouse
spec:
  components:
    - ../../../components/volsync
  dependsOn:
    - name: priority-classes
      namespace: flux-system
  interval: 1h
  path: ./kubernetes/apps/sentry/clickhouse
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_PUID: "101"
      VOLSYNC_PGID: "101"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: sentry
  wait: false
