---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cluster-low
value: -100
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Low priority workloads - can be preempted by normal priority pods"
