---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rimworld
spec:
  components:
    - ../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: external-secrets-store
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/games/rimworld
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      # VOLSYNC_UID: "1000"
      # VOLSYNC_GID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: games
  wait: false
