---
# yaml-language-server: $schema=https://schemas.vzkn.eu/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: terraform
spec:
  interval: 1m
  url: oci://ghcr.io/vrozaksen/manifests/terraform
  ref:
    tag: main
