---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: forgejo-ssh
spec:
  endpoints:
    - dnsName: "ssh.forgejo.vzkn.eu"
      recordType: A
      targets: ["10.10.0.51"]
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'false'
