---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        SECRET_KEY: "{{ .SECRET_KEY }}"
        CF_TURNSTILE_SITEKEY: "{{ .CF_TURNSTILE_SITEKEY }}"
        CF_TURNSTILE_SECRET: "{{ .CF_TURNSTILE_SECRET }}"
        SMTP_ADDR: "{{ .SMTP_ADDR }}"
        USER: "{{ .SMTP_USER }}"
        PASSWD: "{{ .SMTP_PASS }}"
        MINIO_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        MINIO_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: forgejo-bucket
    - extract:
        key: protonmail
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-admin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        username: "{{ .ADMIN_USERNAME }}"
        password: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: forgejo
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        key: "{{ .FORGEJO_CLIENT_ID }}"
        secret: "{{ .FORGEJO_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: forgejo
