---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rxresume-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        # -- Printer (Chrome) --
        CHROME_TOKEN: "{{ .TOKEN }}"
        # -- Auth --
        ACCESS_TOKEN_SECRET: "{{ .ACCESS_TOKEN_SECRET }}"
        REFRESH_TOKEN_SECRET: "{{ .REFRESH_TOKEN_SECRET }}"
        # -- Emails --
        MAIL_FROM: "{{ .SMTP_USER }}"
        SMTP_URL: "smtp://{{ .SMTP_USER }}:{{ .SMTP_PASS }}@{{ .SMTP_HOST }}"
        # -- Storage (Minio) --
        STORAGE_ACCESS_KEY: "{{ .AWS_ACCESS_KEY_ID }}"
        STORAGE_SECRET_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        # -- Email (Optional) --
        DISABLE_SIGNUPS: "false"
        DISABLE_EMAIL_AUTH: "false"
        # -- OpenID (Optional) --
        VITE_OPENID_NAME: Authentik
        OPENID_AUTHORIZATION_URL: "https://sso.vzkn.eu/application/o/authorize/"
        OPENID_CALLBACK_URL: https://rxresume.vzkn.eu/api/auth/openid/callback
        OPENID_CLIENT_ID: "{{ .RXRESUME_CLIENT_ID }}"
        OPENID_CLIENT_SECRET: "{{ .RXRESUME_CLIENT_SECRET }}"
        OPENID_ISSUER: "https://sso.vzkn.eu/application/o/rxresume/"
        OPENID_SCOPE: profile email
        OPENID_TOKEN_URL: "https://sso.vzkn.eu/application/o/token/"
        OPENID_USER_INFO_URL: "https://sso.vzkn.eu/application/o/userinfo/"
  dataFrom:
    - extract:
        key: browserless-chrome
    - extract:
        key: rxresume
    - extract:
        key: rxresume-bucket
    - extract:
        key: protonmail
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name browserless-chrome-secret
spec:
  target:
    name: *name
    template:
      data:
        TOKEN: "{{ .TOKEN }}"
  dataFrom:
    - extract:
        key: browserless-chrome
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
