---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name miniflux-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        ADMIN_USERNAME: "{{ .MINIFLUX_ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .MINIFLUX_ADMIN_PASSWORD }}"
        YOUTUBE_API_KEY: "{{ .MINIFLUX_YOUTUBE_API_KEY }}"
        # Oidc
        OAUTH2_OIDC_PROVIDER_NAME: "Authentik"
        OAUTH2_PROVIDER: "oidc"
        OAUTH2_USER_CREATION: "0"
        OAUTH2_CLIENT_ID: "{{ .MINIFLUX_CLIENT_ID }}"
        OAUTH2_CLIENT_SECRET: "{{ .MINIFLUX_CLIENT_SECRET }}"
        OAUTH2_OIDC_DISCOVERY_ENDPOINT: "https://sso.vzkn.eu/application/o/miniflux/.well-known/openid-configuration"
        OAUTH2_REDIRECT_URL: "https://miniflux.vzkn.eu/oauth2/oidc/callback"
  dataFrom:
    - extract:
        key: miniflux
