---
# yaml-language-server: $schema=https://schemas.vzkn.eu/gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: sentry
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: sentry
  timeout:
    http:
      connectionIdleTimeout: 120s
      requestTimeout: 60s
    tcp:
      connectTimeout: 10s
  connection:
    bufferLimit: 256Ki
