---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sentry
spec:
  components:
    - ../../../components/cnpg/restore
  dependsOn:
    - name: priority-classes
      namespace: flux-system
    - name: cloudnative-pg
      namespace: database
    - name: plugin-barman-cloud
      namespace: database
    - name: dragonfly-operator
      namespace: database
    - name: kafka
      namespace: sentry
    - name: clickhouse
      namespace: sentry
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  interval: 1h
  path: ./kubernetes/apps/sentry/sentry
  postBuild:
    substitute:
      APP: *app
      CNPG_SIZE: 10Gi
      CNPG_POOLER_MODE: transaction
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: sentry
  timeout: 10m
  wait: false
