---
# yaml-language-server: $schema=https://schemas.tholinka.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: 'postgres-${APP}-backup'
spec:
  immediate: true
  backupOwnerReference: self
  schedule: ${CNPG_BACKUP_SCHEDULE:=@daily}
  cluster:
    name: 'postgres-${APP}'
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
