---
# yaml-language-server: $schema=https://schemas.vzkn.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rocketchat-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        # S3 Storage
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        # SMTP Email
        SMTP_HOST: "{{ .SMTP_ADDR }}"
        SMTP_USERNAME: "{{ .SMTP_USER }}"
        SMTP_PASSWORD: "{{ .SMTP_PASS }}"
        SMTP_FROM: "{{ .SMTP_USER }}"
        # OAuth Authentik
        AUTHENTIK_CLIENT_ID: "{{ .ROCKETCHAT_CLIENT_ID }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .ROCKETCHAT_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: rocketchat-bucket
    - extract:
        key: protonmail
