---
# yaml-language-server: $schema=https://schemas.tholinka.dev/barmancloud.cnpg.io/objectstore_v1.json
# technically we only need one of these per namespace...
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-${APP}
spec:
  retentionPolicy: "30d"
  configuration:
    wal:
      compression: bzip2
      maxParallel: 8
    data:
      compression: bzip2
    destinationPath: s3://cnpg/${APP}
    endpointURL: https://api.s3.vzkn.eu
    s3Credentials:
      accessKeyId:
        name: &secret ${APP}-cnpg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: *secret
        key: AWS_SECRET_ACCESS_KEY
