---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
spec:
  components:
    - ../../../../components/cnpg/backup
    - ../../../../components/dragonfly
    - ../../../../components/volsync
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: plugin-barman-cloud
      namespace: database
    - name: dragonfly-operator
      namespace: database
  healthChecks:
    - apiVersion: &postgresVersion postgresql.cnpg.io/v1
      kind: &postgresKind Cluster
      name: postgres-forgejo
      namespace: development
  healthCheckExprs:
    - apiVersion: *postgresVersion
      kind: *postgresKind
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  interval: 1h
  timeout: 10m  # Allow time for CNPG initial backup and startup
  path: ./kubernetes/apps/development/forgejo/app
  postBuild:
    substitute:
      APP: *app
      CNPG_SIZE: 5Gi
      CNPG_REQUESTS_CPU: 100m
      CNPG_LIMITS_MEMORY: 1Gi
      # CNPG_MAX_CONNECTIONS: "100"
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_STORAGECLASS: ceph-block
      VOLSYNC_ACCESSMODES: ReadWriteOnce
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app forgejo-runner
# spec:
#   components:
#     - ../../../../components/volsync
#   dependsOn:
#     - name: forgejo
#   interval: 1h
#   path: ./kubernetes/apps/development/forgejo/runner
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 10Gi
#       VOLSYNC_STORAGECLASS: ceph-block
#       VOLSYNC_ACCESSMODES: ReadWriteOnce
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: false
