---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitea
  annotations:
    gatus.home-operations.com/endpoint: |-
      group: development
spec:
  hostnames: ["gitea.vzkn.eu"]
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - name: gitea-http
          namespace: development
          port: 3000
