---
# yaml-language-server: $schema=https://schemas.vzkn.eu/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - cookie
      - authorization
      - x-forwarded-proto
      - x-forwarded-host
      - x-forwarded-uri
      - x-forwarded-for
    http:
      backendRefs:
        - name: ak-outpost-proxy-outpost
          namespace: security
          port: 9000
      path: /outpost.goauthentik.io/auth/traefik
      headersToBackend:
        - set-cookie
        - x-authentik-username
        - x-authentik-groups
        - x-authentik-email
        - x-authentik-name
        - x-authentik-uid
        - authorization
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${APP}
