---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea
spec:
  components:
    - ../../../components/cnpg/backup
    - ../../../components/dragonfly
    - ../../../components/volsync
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: plugin-barman-cloud
      namespace: database
    - name: dragonfly-operator
      namespace: database
  healthChecks:
    - apiVersion: &postgresVersion postgresql.cnpg.io/v1
      kind: &postgresKind Cluster
      name: postgres-gitea
      namespace: development
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
    - apiVersion: *postgresVersion
      kind: *postgresKind
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/development/gitea
  postBuild:
    substitute:
      APP: *app
      CNPG_SIZE: 5Gi
      CNPG_REQUESTS_CPU: 100m
      CNPG_LIMITS_MEMORY: 1Gi
      # CNPG_MAX_CONNECTIONS: "100"
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_STORAGECLASS: ceph-block
      VOLSYNC_ACCESSMODES: ReadWriteOnce
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
