---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: collabora-websocket
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: nextcloud-collabora
  loadBalancer:
    type: ConsistentHash
    consistentHash:
      type: Cookie
      cookie:
        name: SERVERID
        ttl: 3600s
  timeout:
    http:
      connectionIdleTimeout: 3600s
      requestTimeout: 3600s
    tcp:
      connectTimeout: 30s
