---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nextcloud
spec:
  components:
    - ../../../../components/cnpg/initdb  # PostgreSQL cluster (TODO: change to restore after first install)
    - ../../../../components/dragonfly    # Redis cache (nextcloud-dragonfly)
    - ../../../../components/nfs-scaler   # Scale down on NFS mount issues
    - ../../../../components/volsync      # Backup config/apps volume
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: plugin-barman-cloud
      namespace: database
    - name: dragonfly-operator
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  interval: 1h
  path: ./kubernetes/apps/self-hosted/nextcloud/app
  postBuild:
    substitute:
      APP: *app
      CNPG_SIZE: 10Gi         # PostgreSQL PVC size
      VOLSYNC_CAPACITY: 100Gi # Config/apps backup size (thumbnails, etc)
      VOLSYNC_GID: "100"
      VOLSYNC_UID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-collabora
spec:
  dependsOn:
    - name: nextcloud
      namespace: self-hosted
  interval: 1h
  path: ./kubernetes/apps/self-hosted/nextcloud/collabora
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false
---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-talk
spec:
  dependsOn:
    - name: nextcloud
      namespace: self-hosted
    - name: coturn
      namespace: network
  interval: 1h
  path: ./kubernetes/apps/self-hosted/nextcloud/talk
  postBuild:
    substitute:
      COTURN_PUBLIC_HOST: turn.vzkn.eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false
