---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./collabora-backendpolicy.yaml
  - ./collabora-helmrelease.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./push-helmrelease.yaml
  - ./push-httproute.yaml
  - ./pvc.yaml
