---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud-push
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      push:
        containers:
          app:
            image:
              repository: docker.io/library/nextcloud
              tag: 32.0.2-fpm-alpine@sha256:44da5e764ff8f17e67dd0e7bd9308e87ec6cbf50e3e2086ef02b0a85e23a3539
            command:
              - /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push
              - /var/www/html/config/config.php
            args:
              - --port
              - &port "7867"
            env:
              NEXTCLOUD_URL: http://nextcloud:8080
              PORT: *port

    service:
      app:
        controller: push
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: nextcloud
        globalMounts:
          - path: /var/www/html
            readOnly: true
      data:
        existingClaim: nextcloud-data
        globalMounts:
          - path: /var/www/data
            readOnly: true
